name: ipo
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.6.0
  - pytorch-cuda=12.4
  - pip
  - pip:
    - datasets==3.2.0
    - huggingface-hub==0.26.5
    - tqdm==4.67.1
    - transformers==4.47.0
    - accelerate
    - peft==0.14.0
    - bitsandbytes==0.45.0
    - trl==0.13.0
    - wandb
    - matplotlib
    - seaborn
    - scipy
    - scikit-learn
    # Flash Attention - install separately with: pip install flash-attn --no-build-isolation
    # Make sure PyTorch CUDA version matches system CUDA version first!